# Generated by Django 6.0.6 on 2026-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GAME_DEV', 'Game Development'), ('VLSI', 'VLSI & Chip Design'), ('AI', 'Artificial Intelligence')], max_length=10)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list (e.g., C++, Verilog, PyTorch)', max_length=200)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
